### ISSUE TITLE
La visualizacion de las tareas es diferente

### ISSUE THREAD

**Issue by PaoGalindo** [RedFox-SRL/frontend#112]
### Severidad

Cosmetica

### Prioridad

Baja

### Descripción

Segun mockup esta seccion se llama "estado de tareas" y esta distribuido de cierta forma y en el sistema esta seccion se llama "progreso general de tareas" y esta distribuido de forma totalmente diferente al mockup.

### Pre-condiciones

Navegador Versión 128.0.6613.138 

### Tipo de dispositivo

Computadora

### ¿En qué navegadores encuentras el problema?

Chrome

### Versión del navegador

Navegador Versión 128.0.6613.138 (Build oficial) (64 bits)

### Sistema operativo en el cuál encuentras el problema

Windows

### Pasos

| Paso | Descripción | Input Data |
|------|-------------|------------|
| 1    |             |            |
| 2    |             |            |
| 3    |             |            |
| 4    |             |            |
| 5    |             |            |

### Resultado esperado

Visualizacion de la seccion segun el mockup

### Resultado actual

Visualizacion distinta

### Evidencias

![Captura de pantalla 2024-11-12 185613](https://github.com/user-attachments/assets/39b0a42e-0cca-4964-a54b-e76e3fd75f6d)
![Captura de pantalla 2024-11-12 194136](https://github.com/user-attachments/assets/192e058c-0ee0-49ce-bcc9-665f15049833)

**Comment by Diego3520** [comment]
se cambio totalmente el diseño con respecto al mockup
