### ISSUE TITLE
[User Story]: Visualización del Progreso del Proyecto

### ISSUE THREAD

**Issue by JouleS05** [RedFox-SRL/frontend#17]
### Descripción

**Como** docente, **quiero** poder visualizar la planificación registrada por los equipos y su progreso en tiempo real, **para** ofrecer retroalimentación y asegurar que se mantengan en el camino correcto.

### Criterios de Aceptación

**Acceso a la Planificación:**

- El docente debe poder acceder a la planificación completa de cada equipo desde un panel de control o dashboard, que esté organizado por grupos empresa o equipo.

- La planificación debe incluir hitos, fechas de entrega, tareas asignadas, y dependencias entre tareas, presentadas de manera clara y organizada.

**Visualización del Progreso:**

- El sistema debe mostrar el estado actual de cada tarea dentro de la planificación (por ejemplo, "No Iniciada", "En Progreso", "Completada").

- El sistema debe permitir visualizar el porcentaje de avance general del proyecto, calculado en función de las tareas completadas versus las pendientes.

**Actualización en Tiempo Real:**

- Cualquier cambio en el estado de una tarea o hito realizado por los estudiantes debe reflejarse en tiempo real en la vista del docente.

- El sistema debe mostrar la última fecha y hora de actualización de la planificación para que el docente sepa cuándo se realizaron los últimos cambios.

**Capacidad de Comentarios:**

- El docente debe poder dejar comentarios o retroalimentación directamente sobre tareas específicas o hitos dentro de la planificación, los cuales deben ser visibles para los estudiantes.

- El sistema debe notificar al equipo del proyecto cuando el docente deje un comentario o sugerencia.

### Capturas de Pantalla

**Que mira bobo, anda pa ya**

**Comment by Catiel** [comment]
no sirve tu hu tal vez para iteracion
