### ISSUE TITLE
Tablero de Historias de usuario

### ISSUE THREAD

**Issue by Diego3520** [RedFox-SRL/frontend#2]
### Descripción

**Como** Estudiante, **quiero** poder crear una historia de usuario, **para** colocarlo en el tablero de actividades.

### Criterios de Aceptación
**Verificar** que se puedan ver 5 diferentes columnas en el orden Backlog,  Ready, In progress, In review, Done
**Verificar** que al presionar el botón "+ Add Task" se vea una abra un modal donde ingresar la descripción de la HU
**Verificar** que puedan mover las HU a las distintas columnas
**Verificar** que la HU creada se pueda asignar a un miembro del equipo

### Capturas de Pantalla
-
![Image](https://github.com/user-attachments/assets/0f36f35f-5275-4d15-83a9-ab39c0578c8d)

**Comment by Catiel** [comment]
no es de hu es de tareas por sprint
