### ISSUE TITLE
Realizar la autoevaluacion

### ISSUE THREAD

**Issue by Diego3520** [RedFox-SRL/frontend#41]
### Descripción

**Como** estudiante
**Quiero** poder realizar mi autoevaluación
**Para** para determinar mis puntos fuertes y bajos durante el sprint

### Criterios de Aceptación

verificar los datos del estudiante se reflejen  nombre completo
Verificar que el modal tenga un boton de "Guardar"
 
### Capturas de Pantalla
aun en revision

![Image](https://github.com/user-attachments/assets/1855e232-bee4-48d5-8a23-1a3133689fa7)

**Comment by Catiel** [comment]
tiene que ser individual
